pipeline_name: mikasa-robo
# env
env_name: RememberColor5-v0
abs_action: true
dataset_path: PATH_TO_DATASET/mikasa/RememberColor5-v0
mode: train
max_episode_steps: 90
render_obs_key: 'rgb'
shape_meta:
  action:
    shape:
    - 8
  obs:
    rgb:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    rgb_wrist:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    joints:
      shape:
      - 25
      type: low_dim
action_dim: 8
obs_steps: 2
action_steps: 8
# obs_encoder
rgb_model: resnet18
resize_shape: null
crop_shape:
  - 100
  - 100
random_crop: true
use_group_norm: true
use_seq: true
# train
device: cuda:0
seed: 100
gradient_steps: 600000
batch_size: 64
horizon: 9
nn: chi_transformer
diffusion: ddpm
sample_steps: 50
temperature: 1.0
# optimizer
lr: 0.0001
# eval
model_path: False
num_envs: 10
eval_episodes: 30
save_video: True
eval_freq: 100000
# log
exp_name: ${env_name}/obs_${obs_steps}_act_${action_steps}
save_path: PATH_TO_SAVE_MODEL
project: CleanDiffuser
group: dp_mikasa
wandb_mode: offline
log_freq: 1000
save_freq: 100000
work_dir: ${save_path}/dpptp/${exp_name}/${seed}
# hydra
hydra:
  run:
    dir: ${work_dir}
  job:
    chdir: false



