pipeline_name: dpptp_robomimic
# env
env_name: square
env_type: ph
abs_action: true
dataset_path: PATH_TO_DATASET/robomimic/${env_name}/${env_type}/image_abs.hdf5
mode: train
max_episode_steps: 500
render_obs_key: 'agentview_image'
shape_meta:
  action:
    shape:
    - 10
  obs:
    agentview_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_eef_pos:
      shape:
      - 3
      type: low_dim
    robot0_eef_quat:
      shape:
      - 4
      type: low_dim
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
      type: low_dim
action_dim: 10
obs_steps: 2
action_steps: 8
action_ensemble_samples: 1
# obs_encoder
rgb_model: resnet18
resize_shape: null
crop_shape:
  - 76
  - 76
random_crop: true
use_group_norm: true
use_seq: true
# train
device: cuda:0
seed: 100
gradient_steps: 1000000
batch_size: 64
horizon: 9
nn: chi_transformer
diffusion: ddpm
sample_steps: 50
temperature: 1.0
# optimizer
lr: 0.0001
# eval
model_path: path/to/model
num_envs: 15
eval_episodes: 30
save_video: false
eval_freq: 100000
# mamba
mamba_ssm_cfg:
  d_state: 16
  d_conv: 4
  expand: 2
  dt_rank: "auto"
  dt_min: 0.001
  dt_max: 0.1
  dt_init: "random"
  dt_scale: 1.0
  dt_init_floor: 1e-4
  conv_bias: True
  bias: False
  use_fast_path: True
mamba:
  _target_: cleandiffuser.nn_diffusion.mail.MixerModel
  ssm_cfg: ${mamba_ssm_cfg}
  d_model: 256
  n_layer: 4
  norm_epsilon: 1e-5
  rms_norm: False
  fused_add_norm: False
  residual_in_fp32: False
  device: ${device}
# log
exp_name: ${env_name}_${env_type}/obs_${obs_steps}_act_${action_steps}_emb
save_path: PATH_TO_SAVE_MODEL
project: CleanDiffuser
group: dp_robomimic_multi_modal
wandb_mode: offline
log_freq: 1000
save_freq: 50000
# work_dir: ${save_path}/${pipeline_name}/${mode}/${env_name}/${exp_name}_${now:%Y%m%d_%H%M%S}/${seed}
work_dir: ${save_path}/robomimic/mail/${exp_name}/${seed}
# hydra
hydra:
  run:
    dir: ${work_dir}
  job:
    chdir: false



